version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adaptiserv-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: npm start
